# Generated by Django 3.1.6 on 2021-02-10 17:09

from django.db import migrations
import page.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210210_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=page.fields.ThumbnailImageField(upload_to='photo/%Y/%m'),
        ),
    ]
