# Generated by Django 3.1.5 on 2021-02-09 16:00

from django.db import migrations, models
import django.db.models.deletion
import page.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='NAME')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('category_id', models.ManyToManyField(to='page.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='TIME')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.category')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.member')),
                ('tag_id', models.ManyToManyField(to='page.Tag')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('image', page.fields.ThumbnailImageField(upload_to='photo/%Y/%m')),
                ('content', models.TextField(blank=True, verbose_name='CONTENT')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.member')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.post')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
