# Generated by Django 3.1.5 on 2021-02-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='member',
        ),
    ]
