# Generated by Django 3.1.5 on 2021-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20210208_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, to='page.Category'),
        ),
    ]
