# Generated by Django 3.1.5 on 2021-02-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210204_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Member ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.post'),
        ),
    ]
