# Generated by Django 3.1.5 on 2021-02-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210204_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.post'),
        ),
    ]
