# Generated by Django 3.1.5 on 2021-02-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210205_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=111, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=111, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='TIME'),
        ),
    ]
